### ISSUE TITLE
Help on deploying graphite_exporter inside the graphite pod

### ISSUE THREAD

**Issue by Ferdinanddb** [kiwigrid/helm-charts#180]
Hello, this is not a technical issue. I don't have a lot of experience with the following kind of "issues" so I thought that someone might be able to help me if I'm not the only one doing it: 

I would like to know if there is a way to run [graphite_exporter](https://github.com/prometheus/graphite_exporter) inside my graphite pod that I deploy with your Helm chart. I tried to do it by hand but the git & make packages are not present in the container.

**Comment by axdotl** [comment]
Hi @Ferdinanddb, the recommended way to achieve this is adding an additional container to the pod - a so called sidecar. (checkout the k8s docu in this: https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/). Furthermore it's not a good idea to manipulate a running pod (actually this should not possible at all due security reasons), because once this pod is re-started or re-scheduled - all you manual changes will be lost.

Unfortunately, the graphite chart itself currently not supporting extra or additional containers, because it was not required. But you can create a PR for this (an example how to deal with extraContainers can be found in this Keycloak chart: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak).
