### ISSUE TITLE
Elasticsearch Breaking Changes

### ISSUE THREAD

**Issue by gregdhill** [kiwigrid/helm-charts#56]
## fluentd-elasticsearch (version: 2.5.0)

Upstream elasticsearch has introduced a number of breaking changes (as discussed [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types)). This can be trivially solved by changing `_doc` to `doc` in the default config [here](https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L578), but there may be more issues that I've yet to come across.

**Comment by monotek** [comment]
As i understood the docs "_doc" is prefered in ES 6.0.

The 7.0 chapter says: 
"Specifying types in requests is deprecated. For instance, indexing a document no longer requires a document type."
So my understanding is that the type is ignored in 7.0.
Where do you read "doc" instead of "_doc" should be used?

**Comment by gregdhill** [comment]
I'm not convinced this was actually what solved my original problem, so I'm going to close this issue for now.
